object Versions {
    const val kotlin = "1.8.10"
    const val hilt = "2.44.2"
    const val hiltNavigation = "1.0.0"
    const val ksp = "1.8.10-1.0.9"
    const val kotlinSerializationJson = "1.5.0"

    const val appCompat = "1.6.1"
    const val coreKtx = "1.9.0"
    const val navigationUiKtx = "2.5.3"
    const val lifecycle = "2.6.1"
    const val splashScreen = "1.0.0"

    const val composeKotlinCompiler = "1.4.4"
    const val compose = "1.4.0"
    const val composeNavigation = "2.5.3"
    const val composeMaterialIcons = "1.4.0"
    const val activityCompose = "1.7.0"
    const val composeMaterial2 = "1.4.0"
    const val composeMaterial3 = "1.1.0-beta01"
    const val composeDestination = "1.8.38-beta"
    const val composeConstraintLayout = "1.0.1"
    const val accompanist = "0.30.0"
    const val coilCompose = "2.3.0"
    const val calendarCompose = "2.2.1-SNAPSHOT"

    const val room = "2.5.1"
    const val dataStorePreferences = "1.0.0"
    const val okio = "3.3.0"
    const val retrofit = "2.9.0"
    const val moshi = "1.14.0"

    const val desugarJdkLibs = "2.0.2"
    const val commonsIo = "2.6"
    const val compressor = "3.0.1"

    const val timber = "4.7.1"
    const val jUnit = "4.12"
    const val gradle = "8.0.1"
}
