import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.6.1" // available: "0.7.0"

    const val com_android_tools_build_gradle: String = "4.0.0"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val org_jetbrains_kotlinx: String = "1.3.7"

    const val org_jetbrains_kotlin: String = "1.3.72"

    const val androidx_navigation: String = "2.2.2"

    const val androidx_lifecycle: String = "2.2.0"

    const val com_squareup_moshi: String = "1.9.3"

    const val com_google_dagger: String = "2.28-alpha"

    const val constraintlayout: String = "1.1.3"

    const val androidx_hilt: String = "1.0.0-alpha01"

    const val androidx_room: String = "2.2.5"

    const val espresso_core: String = "3.2.0"

    const val activity_ktx: String = "1.2.0-alpha06"

    const val fragment_ktx: String = "1.3.0-alpha06"

    const val junit_junit: String = "4.12" // available: "4.13"

    const val lint_gradle: String = "27.0.0"

    const val appcompat: String = "1.1.0"

    const val core_ktx: String = "1.3.0"

    const val aapt2: String = "4.0.0-6051327"

    /**
     * Current version: "6.2.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.5"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
