package com.sayler.monia.util

object Constants {
    val DATA_PATTERN_DAY_NUMBER_DAY_OF_WEEK = "d, EEEE"
    val DATE_PATTERN_YEAR_MONTH_2_LINES = "YYYY \nMMMM"
    val DATE_PATTERN_YEAR_MONTH = "YYYY MMMM"

    val EXTRA_DAY_ID = "EXTRA_DAY_ID"
    val EXTRA_EDIT_MODE = "EXTRA_EDIT_MODE"
    val EXTRA_NEW_DAY = "EXTRA_NEW_DAY"

    val REQUEST_CODE_SELECT_ATTACHMENT = 4116
    val REQUEST_CODE_EDIT_DAY = 3454

    val REQUEST_CODE_SELECT_DB = 4650
    val BROADCAST_EDIT_DAY = "BROADCAST_EDIT_DAY"
    val BROADCAST_DELETE_DAY = "BROADCAST_DELETE_DAY"

    val PREFERENCES = "PREFERENCES_KEY"
    val PREF_SETTINGS_STORE = "PREF_SETTINGS_STORE"
}
